- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  #- name: Stop the http_server1 container
    #docker_container:
      #name: rahul9711/finance_me:1.0
      #state: stopped

  - name: Remove Existing  Container
    command: sudo docker rm rahul9711/finance_me:1.0

  - name: Deploy Docker Container
    command: sudo docker run -itd -p 8084:8081 rahul9711/finance_me:1.0
